name: pet_adoption_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  flutter_riverpod: ^2.3.6
  confetti: ^0.7.0
  connectivity_plus: ^4.0.0
  mockito: ^5.4.0
  nock: ^1.2.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
